### ISSUE TITLE
🐞 blank suggestions when adding a new filter with IN operator

### ISSUE THREAD

**Issue by Tavh** [teletrace/teletrace#1008] opened 2023-01-10 13:48 UTC
## Describe the Bug

When trying to add a filter of type IN, there are sometimes blank suggestions

## Steps To Reproduce

1. Go to https://app.embedded.lupaproject.io
2. Click on "Add filter"
3. Choose a key such as span.traceState
4. Choose "IN" operator
5. Open the value suggestions
6. There might be a blank string as a suggestion

## Expected Behavior

Either there shouldn't be a suggestion at all or there should be some indication that this is a blank value

## Tasks

- [ ] Investigate
- [ ] Fix

## Environment:

- Infrastructure: Laptop
- Browser: safari
## Screenshots

![Screenshot 2023-01-10 at 15 45 45](https://user-images.githubusercontent.com/44731477/211568234-fcf46165-64d8-4ab0-9973-f0f15ad03a91.png)

**Comment by haimrait** [comment] 2023-03-26 07:58
duplicate of #1119

**Closed by haimrait** 2023-03-26 07:58 UTC
Labels: Type: Bug
