### ISSUE TITLE
🐞  Filter values are empty

### ISSUE THREAD

**Issue by haddasbronfman** [teletrace/teletrace#1064] opened 2023-01-10 14:14 UTC
Cc:

Hi

## Describe the Bug

Select the following filter: 

<img width="553" alt="image" src="https://user-images.githubusercontent.com/85441461/211573829-38e09076-74ff-4e4f-8606-102912a68d88.png">

from the available values (which is only 0) - choose 0. 

The result is that we see an empty filter:

![image](https://user-images.githubusercontent.com/85441461/211574224-abf72394-6bcf-4785-984e-db785fd3d5ee.png)

in addition, the "No options" at the bottom is is"jumping" and shows "loading..." 

## Tasks

- [ ] Investigate
- [ ] Fix

## Environment:

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
- Deployment tool: [e.g., helm]
- Browser: [e.g. chrome, safari]

**Comment by haimrait** [comment] 2023-03-26 07:49
Duplicate of #1119

**Closed by haimrait** 2023-03-26 07:49 UTC
Labels: Type: Bug
